# Generated by Django 5.2.12 on 2026-03-07 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='processed_at',
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Kutilmoqda'), ('paid', "To'langan"), ('COMPLETED', 'Bajarildi'), ('CANCELLED', 'Bekor qilindi')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('SUCCESS', 'Muvaffaqiyatli'), ('FAILED', 'Muvaffaqiyatsiz'), ('REFUNDED', 'Qaytarildi')], default='SUCCESS', max_length=20),
        ),
    ]
