from environs import Env
env = Env()
env.read_env('.env')


# -- DJANGO --
DEBUG = env.bool('DEBUG', False)
DJANGO_SECRET_KEY = env.bool('DEBUG', False)


# -- POSTGRES --
POSTGRES_DB = env('POSTGRES_DB')
POSTGRES_USER = env('POSTGRES_USER')
POSTGRES_PASSWORD = env('POSTGRES_PASSWORD')
POSTGRES_HOST = env('POSTGRES_HOST')
POSTGRES_PORT = env('POSTGRES_PORT')


# -- CELERY --
CELERY_BROKER_URL = env("CELERY_BROKER_URL")
CELERY_RESULT_URL = env("CELERY_RESULT_URL")


# -- WEBHOOK --
WEBHOOK_SECRET = env("WEBHOOK_SECRET")


# -- EXCHANGE RATE --
EXCHANGE_RATE_BASE_URL = env("EXCHANGE_RATE_BASE_URL")
EXCHANGE_RATE_API_KEY = env("EXCHANGE_RATE_API_KEY")